import { normalizeSubstanciaKey } from './substancias'

export type FamiliaMineralId =
  | 'metais_ferrosos'
  | 'metais_preciosos'
  | 'metais_base'
  | 'minerais_estrategicos'
  | 'minerais_industriais'
  | 'rochas_ornamentais'
  | 'materiais_construcao'
  | 'gemas_pedras'
  | 'energeticos'
  | 'aguas_minerais'
  | 'outros'

export interface FamiliaMineralDef {
  id: FamiliaMineralId
  label: string
  color: string
  substancias: string[]
}

type FamiliaMineralRaw = Omit<FamiliaMineralDef, 'substancias'> & {
  substanciasRaw: string[]
}

const RAW: FamiliaMineralRaw[] = [
    {
      id: 'metais_ferrosos',
      label: 'Metais Ferrosos',
      color: '#7EADD4',
      substanciasRaw: [
        'FERRO',
        'FERRO MANGANÊS',
        'HEMATITA',
        'MAGNETITA',
        'ITABIRITO',
        'LATERITA FERRUGINOSA',
        'MANGANÊS',
        'CROMO',
        'CROMITA',
        'MINÉRIO DE FERRO',
        'MINÉRIO DE MANGANÊS',
        'MINÉRIO DE CROMO',
        'TITÂNIO',
        'TITANITA',
        'ILMENITA',
        'RUTILO',
        'MINÉRIO DE TITÂNIO',
        'VANÁDIO',
        'MINÉRIO DE VANÁDIO',
        'CANGA',
      ],
    },
    {
      id: 'metais_preciosos',
      label: 'Metais Preciosos',
      color: '#D4A843',
      substanciasRaw: [
        'OURO',
        'OURO NATIVO',
        'OURO PIGMENTO',
        'PRATA',
        'PLATINA',
        'PALÁDIO',
        'ALUVIÃO AURÍFERO',
        'MINÉRIO DE OURO',
        'MINÉRIO DE PRATA',
        'MINÉRIO DE PLATINA',
        'MINÉRIO DE PALÁDIO',
      ],
    },
    {
      id: 'metais_base',
      label: 'Metais Base',
      color: '#C87C5B',
      substanciasRaw: [
        'COBRE',
        'ZINCO',
        'CHUMBO',
        'ESTANHO',
        'NÍQUEL',
        'CASSITERITA',
        'GALENA',
        'ALUVIÃO ESTANÍFERO',
        'MINÉRIO DE COBRE',
        'MINÉRIO DE ZINCO',
        'MINÉRIO DE CHUMBO',
        'MINÉRIO DE ESTANHO',
        'MINÉRIO DE NÍQUEL',
        'SILICATOS DE NÍQUEL',
        'SULFETOS DE CHUMBO',
        'MOLIBDÊNIO',
        'MOLIBDENITA',
        'MINÉRIO DE MOLIBDÊNIO',
        'BISMUTO',
        'MINÉRIO DE BISMUTO',
        'ARSÊNIO',
        'MINÉRIO DE ARSÊNICO',
        'CÁDMIO',
        'MINÉRIO DE CÁDMIO',
        'ANTIMÔNIO',
        'MINÉRIO DE ANTIMÔNIO',
        'MERCÚRIO',
        'MINÉRIO DE MERCÚRIO',
        'TUNGSTÊNIO',
        'WOLFRAMITA',
        'SCHEELITA',
        'MINÉRIO DE TUNGSTÊNIO',
      ],
    },
    {
      id: 'minerais_estrategicos',
      label: 'Minerais Estratégicos',
      color: '#5CBFA0',
      substanciasRaw: [
        'NIÓBIO',
        'PIROCLORO',
        'COLUMBITA',
        'LÍTIO',
        'ESPODUMÊNIO',
        'LEPIDOLITA',
        'PETALITA',
        'AMBLIGONITA',
        'MINÉRIO DE LÍTIO',
        'MINÉRIO DE NIÓBIO',
        'TERRAS RARAS',
        'MONAZITA',
        'MINÉRIO DE CÉRIO',
        'TÂNTALO',
        'TANTALITA',
        'TANTALITA-COLUMBITA',
        'MINÉRIO DE TÂNTALO',
        'BERÍLIO',
        'BERILO',
        'MINÉRIO DE BERÍLIO',
        'ZIRCÔNIO',
        'ZIRCÃO',
        'ZIRCONITA',
        'MINÉRIO DE ZIRCÔNIO',
        'HÁFNIO',
        'GRAFITA',
        'MINÉRIO DE COBALTO',
        'MINÉRIO DE CÉSIO',
        'POLUCITA',
        'MINÉRIO DE RUBÍDIO',
        'MINÉRIO DE SILÍCIO',
        'MINÉRIO DE URÂNIO',
        'ESTRÔNCIO',
      ],
    },
    {
      id: 'minerais_industriais',
      label: 'Minerais Industriais',
      color: '#9B8EC4',
      substanciasRaw: [
        'QUARTZO',
        'QUARTZO INDUSTRIAL',
        'CRISTAL DE ROCHA',
        'SÍLICA',
        'SÍLEX',
        'BAUXITA',
        'BAUXITA FOSFOROSA',
        'GIBBSITA',
        'HIDRARGILITA',
        'MINÉRIO DE ALUMÍNIO',
        'ALUMÍNIO',
        'FELDSPATO',
        'NEFELINA',
        'NEFELINA SIENITO',
        'CAULIM',
        'CAULIM ARGILOSO',
        'CAULINITA',
        'TALCO',
        'ESTEATITO',
        'PIROFILITA',
        'AGALMATOLITO',
        'MICA',
        'MOSCOVITA',
        'BIOTITA GRANITO',
        'CALCITA',
        'DOLOMITO',
        'MAGNESITA',
        'MAGNÉSIO',
        'MINÉRIO DE MAGNÉSIO',
        'SAIS DE MAGNÉSIO',
        'BARITA',
        'FLUORITA',
        'APATITA',
        'FOSFATO',
        'FOSFORITA (O)',
        'ROCHA FOSFÁTICA',
        'GIPSITA',
        'GIPSO',
        'ANIDRITA',
        'BENTONITA',
        'ARGILA BENTONÍTICA',
        'MONTMORILONITA',
        'SAPONITA',
        'ATAPULGITA',
        'DIATOMITA',
        'DIATOMITO',
        'TRIPOLITO',
        'VERMICULITA',
        'BORATOS',
        'ENXOFRE',
        'PIRITA',
        'SALGEMA',
        'SILVINITA',
        'CARNALITA',
        'SAIS DE POTÁSSIO',
        'NITRATO DE POTÁSSIO',
        'ROCHA POTÁSSICA',
        'SAIS DE SÓDIO',
        'SAIS DE BROMO',
        'LEUCITA',
        'CIANITA',
        'ANDALUZITA',
        'CORDIERITA',
        'CORÍNDON',
        'OLIVINA',
        'ANTOFILITA',
        'ANFIBÓLIO',
        'GRANADA',
        'OCRE',
        'GUANO',
        'ALGAS CALCÁREAS',
        'CONCHAS CALCÁRIAS',
        'PEDRA CALCÁRIA',
        'SAPROPELITO',
        'DIOPSÍDIO',
        'PIROXENITO',
        'DUNITO',
      ],
    },
    {
      id: 'rochas_ornamentais',
      label: 'Rochas Ornamentais',
      color: '#B8917A',
      substanciasRaw: [
        'GRANITO',
        'GRANITO ORNAMENTAL',
        'GRANITO P/ REVESTIMENTO',
        'GRANITO P/ BRITA',
        'GRANITO GNÁISSICO',
        'BIOTITA GRANITO',
        'SIENO GRANITO',
        'MÁRMORE',
        'MÁRMORE DOLOMÍTICO',
        'MÁRMORE P/ REVESTIMENTO',
        'GNAISSE',
        'GNAISSE ORNAMENTAL',
        'GNAISSE P/ REVESTIMENTO',
        'GNAISSE INDUSTRIAL',
        'GNAISSE P/ BRITA',
        'ARDÓSIA',
        'QUARTZITO',
        'QUARTZITO P/ REVESTIMENTO',
        'QUARTZITO INDUSTRIAL',
        'QUARTZITO FRIÁVEL',
        'QUARTZITO SERICITICO',
        'MIGMATITO',
        'MIGMATITO ORNAMENTAL',
        'MIGMATITO P/ BRITA',
        'MIGMATITO INDUSTRIAL',
        'GRANODIORITO',
        'GRANODIORITO INDUSTRIAL',
        'GRANODIORITO P/ REVESTIMENTO',
        'SIENITO',
        'SIENITO ORNAMENTAL',
        'SIENITO INDUSTRIAL',
        'PEDRA ORNAMENTAL',
        'PEDRA CORADA',
        'SODALITA',
        'SODALITA SIENITO',
        'SERPENTINITO',
        'LEUCOFILITO',
      ],
    },
    {
      id: 'materiais_construcao',
      label: 'Materiais de Construção',
      color: '#888780',
      substanciasRaw: [
        'AREIA',
        'AREIA COMUM',
        'AREIA LAVADA',
        'AREIA FLUVIAL',
        'AREIA ALUVIONAR',
        'AREIA INDUSTRIAL',
        'AREIA IN NATURA',
        'AREIA QUARTZOSA',
        'AREIA DE FUNDIÇÃO',
        'AREIA P/ VIDRO',
        'ARGILA',
        'ARGILA COMUM',
        'ARGILA VERMELHA',
        'ARGILA P/CER. VERMELH',
        'ARGILA BRANCA',
        'ARGILA ALUMINOSA',
        'ARGILA CAULÍNICA',
        'ARGILA FERRUGINOSA',
        'ARGILA REFRATÁRIA',
        'ARGILITO',
        'CALCÁRIO',
        'CALCÁRIO CALCÍTICO',
        'CALCÁRIO DOLOMÍTICO',
        'CALCÁRIO MAGNESIANO',
        'CALCÁRIO INDUSTRIAL',
        'CALCÁRIO P/ BRITA',
        'CALCÁRIO CONCHÍFERO',
        'CALCÁRIO CORALÍNEO',
        'BRITA DE GRANITO',
        'CASCALHO',
        'CASCALHO SILICOSO',
        'PEDREGULHO',
        'SEIXOS',
        'SEIXOS ROLADOS',
        'SAIBRO',
        'BASALTO',
        'BASALTO P/ BRITA',
        'BASALTO P/ REVESTIMENTO',
        'DIABÁSIO',
        'DIABÁSIO P/ BRITA',
        'DIABÁSIO P/ REVESTIMENTO',
        'DIORITO',
        'DIORITO P/ BRITA',
        'TONALITO',
        'MONZONITO',
        'ARENITO',
        'ARCÓSIO',
        'SILTITO',
        'CONGLOMERADO',
        'METACONGLOMERADO',
        'FILITO',
        'MICAXISTO',
        'ANFIBOLITO',
        'LATERITA',
        'VARVITO',
        'ANDESITO',
        'ANORTOSITO',
        'CHARNOQUITO',
        'ENDERBITO',
        'DACITO',
        'RIÓLITO',
        'TRAQUITO',
        'FONÓLITO',
        'TINGUAÍTO',
        'TUFO',
        'TUFO VULCÂNICO',
        'GABRO',
        'GRANULITO',
        'KINZIGITO',
        'CATACLASITO',
        'PEGMATITO',
        'XISTO',
        'XISTO ARGILOSO',
      ],
    },
    {
      id: 'gemas_pedras',
      label: 'Gemas e Pedras Preciosas',
      color: '#E07A9E',
      substanciasRaw: [
        'DIAMANTE',
        'DIAMANTE INDUSTRIAL',
        'CASCALHO DIAMANTÍFERO',
        'ESMERALDA',
        'RUBI',
        'SAFIRA',
        'ÁGUA MARINHA',
        'MORGANITA',
        'CRISOBERILO',
        'ALEXANDRITA',
        'TOPÁZIO',
        'TOPÁZIO IMPERIAL',
        'TURMALINA',
        'TURQUESA',
        'AMETISTA',
        'CITRINO',
        'ÁGATA',
        'CALCEDÔNIA',
        'OPALA',
        'CRISOPRÁSIO',
        'KUNZITA',
        'AMAZONITA',
        'GEMA',
      ],
    },
    {
      id: 'energeticos',
      label: 'Energéticos',
      color: '#D4783C',
      substanciasRaw: [
        'CARVÃO',
        'CARVÃO MINERAL',
        'ANTRACITO',
        'LINHITO',
        'TURFA',
        'FOLHELHO',
        'FOLHELHO ARGILOSO',
        'FOLHELHO BETUMINOSO',
        'FOLHELHO PIROBETUMINO',
        'ARENITO BETUMINOSO',
        'ROCHA BETUMINOSA',
        'ROCHA PIROBETUMINOSA',
      ],
    },
    {
      id: 'aguas_minerais',
      label: 'Águas Minerais',
      color: '#4A90B8',
      substanciasRaw: [
        'ÁGUA MINERAL',
        'ÁGUA MINERAL ALC. BIC',
        'ÁGUA MINERAL ALC. TER. CALCI.',
        'ÁGUA MINERAL CARBOGAS',
        'ÁGUA MINERAL RAD. FON',
        'ÁGUA POTÁVEL DE MESA',
        'ÁGUA TERMO MINERAL',
        'ÁGUAS OLIGOMINERAIS',
        'ÁGUAS TERMAIS',
      ],
    },
    {
      id: 'outros',
      label: 'Outros',
      color: '#6B6B65',
      substanciasRaw: ['DADO NÃO CADASTRADO'],
    },
  ]

function uniqNorm(list: string[]): string[] {
  const seen = new Set<string>()
  const out: string[] = []
  for (const s of list) {
    const k = normalizeSubstanciaKey(s)
    if (!seen.has(k)) {
      seen.add(k)
      out.push(k)
    }
  }
  return out
}

export const FAMILIA_MINERAL_DEFS: FamiliaMineralDef[] = RAW.map((row) => {
  const { substanciasRaw, ...rest } = row
  return {
    ...rest,
    substancias: uniqNorm(substanciasRaw),
  }
})

export function getFamiliaBySubstancia(substanciaKeyNorm: string): FamiliaMineralDef {
  for (const fam of FAMILIA_MINERAL_DEFS) {
    if (fam.substancias.includes(substanciaKeyNorm)) return fam
  }
  return FAMILIA_MINERAL_DEFS[FAMILIA_MINERAL_DEFS.length - 1]
}

export function corPorFamilia(substanciaRaw: string): string {
  const key = normalizeSubstanciaKey(substanciaRaw)
  return getFamiliaBySubstancia(key).color
}
